### ISSUE TITLE
It doesn't work with the latest version of Airflow (tested with 2.5.3)

### ISSUE THREAD

**Issue by lopezvit** [mendhak/Airflow-MS-Teams-Operator#15]
With the current code I get a warning and an error when I try to execute it:
`[2023-11-27, 21:14:48 UTC] {warnings.py:109} WARNING - /opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py:394: AirflowProviderDeprecationWarning: Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use ``HttpOperator`` instead.`

```
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1544, in _run_finished_callback
    callback(context)
  File "/home/airflow/gcs/dags/LikeIT/src/dags_utils.py", line 19, in send_teams_message
    teams_notification = MSTeamsWebhookOperator(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/utils/decorators.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/gcs/dags/LikeIT/src/ms_teams_webhook_operator.py", line 74, in __init__
    self.hook = None
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 981, in __setattr__
    super().__setattr__(key, value)
AttributeError: can't set attribute
```

Fixed already, will create a PR with the changes.

**Comment by mendhak** [comment]
Forgot to close this, thanks for [the PR](https://github.com/mendhak/Airflow-MS-Teams-Operator/pull/16).
